# DO NOT EDIT THIS FILE!
#
# Python module DataBase generated by omniidl

import omniORB
omniORB.updateModule("DataBase")

# ** 1. Stub files contributing to this module
import DataBase_idl

# ** 2. Sub-modules

# ** 3. End
