cd /d %~dp0
cmd /c AbsFunction\BuildRelease.bat
cmd /c ArmController\BuildRelease.bat
cmd /c artp\BuildRelease.bat
cmd /c Backlash\BuildRelease.bat
cmd /c Bias\BuildRelease.bat
cmd /c CapturePresentation\BuildRelease.bat
cmd /c ConstantValue\BuildRelease.bat
cmd /c ConvertImage\BuildRelease.bat
cmd /c CoulombAndViscousFriction\BuildRelease.bat
cmd /c DeadZone\BuildRelease.bat
cmd /c DemuxFunction\BuildRelease.bat
cmd /c Derivative\BuildRelease.bat
cmd /c Gain\BuildRelease.bat
cmd /c IfElse\BuildRelease.bat
cmd /c Integrator\BuildRelease.bat
cmd /c MinMaxFunction\BuildRelease.bat
cmd /c MuxFunction\BuildRelease.bat
cmd /c PIDController\BuildRelease.bat
cmd /c Polynomial\BuildRelease.bat
cmd /c PresentationView\BuildRelease.bat
cmd /c ProductFunction\BuildRelease.bat
cmd /c PulseGenerator\BuildRelease.bat
cmd /c RampFunction\BuildRelease.bat
cmd /c RandomNumber\BuildRelease.bat
cmd /c RateLimiter\BuildRelease.bat
cmd /c Relay\BuildRelease.bat
cmd /c RMC\BuildRelease.bat
cmd /c RobotArmSimulator\BuildRelease.bat
cmd /c Saturation\BuildRelease.bat
cmd /c Scope\BuildRelease.bat
cmd /c SignFunction\BuildRelease.bat
cmd /c SineWave\BuildRelease.bat
cmd /c SqrtFunction\BuildRelease.bat
cmd /c StepFunction\BuildRelease.bat
cmd /c SumFunction\BuildRelease.bat
cmd /c TrigonometricFunction\BuildRelease.bat
cmd /c UnaryMinus\BuildRelease.bat
cmd /c UniformRandomNumber\BuildRelease.bat
cmd /c WrapToZero\BuildRelease.bat
cmd /c MyFirstComponent\BuildRelease.bat
