cd /d %~dp0
cmd /c AbsFunction\BuildDebug.bat
cmd /c ArmController\BuildDebug.bat
cmd /c artp\BuildDebug.bat
cmd /c Backlash\BuildDebug.bat
cmd /c Bias\BuildDebug.bat
cmd /c CapturePresentation\BuildDebug.bat
cmd /c ConstantValue\BuildDebug.bat
cmd /c ConvertImage\BuildDebug.bat
cmd /c CoulombAndViscousFriction\BuildDebug.bat
cmd /c DeadZone\BuildDebug.bat
cmd /c DemuxFunction\BuildDebug.bat
cmd /c Derivative\BuildDebug.bat
cmd /c Gain\BuildDebug.bat
cmd /c IfElse\BuildDebug.bat
cmd /c Integrator\BuildDebug.bat
cmd /c MinMaxFunction\BuildDebug.bat
cmd /c MuxFunction\BuildDebug.bat
cmd /c PIDController\BuildDebug.bat
cmd /c Polynomial\BuildDebug.bat
cmd /c PresentationView\BuildDebug.bat
cmd /c ProductFunction\BuildDebug.bat
cmd /c PulseGenerator\BuildDebug.bat
cmd /c RampFunction\BuildDebug.bat
cmd /c RandomNumber\BuildDebug.bat
cmd /c RateLimiter\BuildDebug.bat
cmd /c Relay\BuildDebug.bat
cmd /c RMC\BuildDebug.bat
cmd /c RobotArmSimulator\BuildDebug.bat
cmd /c Saturation\BuildDebug.bat
cmd /c Scope\BuildDebug.bat
cmd /c SignFunction\BuildDebug.bat
cmd /c SineWave\BuildDebug.bat
cmd /c SqrtFunction\BuildDebug.bat
cmd /c StepFunction\BuildDebug.bat
cmd /c SumFunction\BuildDebug.bat
cmd /c TrigonometricFunction\BuildDebug.bat
cmd /c UnaryMinus\BuildDebug.bat
cmd /c UniformRandomNumber\BuildDebug.bat
cmd /c WrapToZero\BuildDebug.bat
cmd /c MyFirstComponent\BuildDebug.bat
