#!/bin/sh
cd `dirname $0`
sh AbsFunction/BuildRelease.sh
sh ArmController/BuildRelease.sh
sh artp/BuildRelease.sh
sh Backlash/BuildRelease.sh
sh Bias/BuildRelease.sh
sh CapturePresentation/BuildRelease.sh
sh ConstantValue/BuildRelease.sh
sh ConvertImage/BuildRelease.sh
sh CoulombAndViscousFriction/BuildRelease.sh
sh DeadZone/BuildRelease.sh
sh DemuxFunction/BuildRelease.sh
sh Derivative/BuildRelease.sh
sh Gain/BuildRelease.sh
sh IfElse/BuildRelease.sh
sh Integrator/BuildRelease.sh
sh MinMaxFunction/BuildRelease.sh
sh MuxFunction/BuildRelease.sh
sh PIDController/BuildRelease.sh
sh Polynomial/BuildRelease.sh
sh PresentationView/BuildRelease.sh
sh ProductFunction/BuildRelease.sh
sh PulseGenerator/BuildRelease.sh
sh RampFunction/BuildRelease.sh
sh RandomNumber/BuildRelease.sh
sh RateLimiter/BuildRelease.sh
sh Relay/BuildRelease.sh
sh RMC/BuildRelease.sh
sh RobotArmSimulator/BuildRelease.sh
sh Saturation/BuildRelease.sh
sh Scope/BuildRelease.sh
sh SignFunction/BuildRelease.sh
sh SineWave/BuildRelease.sh
sh SqrtFunction/BuildRelease.sh
sh StepFunction/BuildRelease.sh
sh SumFunction/BuildRelease.sh
sh TrigonometricFunction/BuildRelease.sh
sh UnaryMinus/BuildRelease.sh
sh UniformRandomNumber/BuildRelease.sh
sh WrapToZero/BuildRelease.sh
sh MyFirstComponent/BuildRelease.sh
