cd /d %~dp0
cmd /c AbsFunction\Install.bat
cmd /c ArmController\Install.bat
cmd /c artp\Install.bat
cmd /c Backlash\Install.bat
cmd /c Bias\Install.bat
cmd /c CapturePresentation\Install.bat
cmd /c ConstantValue\Install.bat
cmd /c ConvertImage\Install.bat
cmd /c CoulombAndViscousFriction\Install.bat
cmd /c DeadZone\Install.bat
cmd /c DemuxFunction\Install.bat
cmd /c Derivative\Install.bat
cmd /c Gain\Install.bat
cmd /c IfElse\Install.bat
cmd /c Integrator\Install.bat
cmd /c MinMaxFunction\Install.bat
cmd /c MuxFunction\Install.bat
cmd /c PIDController\Install.bat
cmd /c Polynomial\Install.bat
cmd /c PresentationView\Install.bat
cmd /c ProductFunction\Install.bat
cmd /c PulseGenerator\Install.bat
cmd /c RampFunction\Install.bat
cmd /c RandomNumber\Install.bat
cmd /c RateLimiter\Install.bat
cmd /c Relay\Install.bat
cmd /c RMC\Install.bat
cmd /c RobotArmSimulator\Install.bat
cmd /c Saturation\Install.bat
cmd /c Scope\Install.bat
cmd /c SignFunction\Install.bat
cmd /c SineWave\Install.bat
cmd /c SqrtFunction\Install.bat
cmd /c StepFunction\Install.bat
cmd /c SumFunction\Install.bat
cmd /c TrigonometricFunction\Install.bat
cmd /c UnaryMinus\Install.bat
cmd /c UniformRandomNumber\Install.bat
cmd /c WrapToZero\Install.bat
cmd /c MyFirstComponent\Install.bat
cmd /c testEC\Install.bat
