#!/bin/sh
cd `dirname $0`
sh AbsFunction/unInstall.sh
sh ArmController/unInstall.sh
sh artp/unInstall.sh
sh Backlash/unInstall.sh
sh Bias/unInstall.sh
sh CapturePresentation/unInstall.sh
sh ConstantValue/unInstall.sh
sh ConvertImage/unInstall.sh
sh CoulombAndViscousFriction/unInstall.sh
sh DeadZone/unInstall.sh
sh DemuxFunction/unInstall.sh
sh Derivative/unInstall.sh
sh Gain/unInstall.sh
sh IfElse/unInstall.sh
sh Integrator/unInstall.sh
sh MinMaxFunction/unInstall.sh
sh MuxFunction/unInstall.sh
sh PIDController/unInstall.sh
sh Polynomial/unInstall.sh
sh PresentationView/unInstall.sh
sh ProductFunction/unInstall.sh
sh PulseGenerator/unInstall.sh
sh RampFunction/unInstall.sh
sh RandomNumber/unInstall.sh
sh RateLimiter/unInstall.sh
sh Relay/unInstall.sh
sh RMC/unInstall.sh
sh RobotArmSimulator/unInstall.sh
sh Saturation/unInstall.sh
sh Scope/unInstall.sh
sh SignFunction/unInstall.sh
sh SineWave/unInstall.sh
sh SqrtFunction/unInstall.sh
sh StepFunction/unInstall.sh
sh SumFunction/unInstall.sh
sh TrigonometricFunction/unInstall.sh
sh UnaryMinus/unInstall.sh
sh UniformRandomNumber/unInstall.sh
sh WrapToZero/unInstall.sh
sh MyFirstComponent/unInstall.sh
