cd /d %~dp0
cmd /c AbsFunction\unInstall.bat
cmd /c ArmController\unInstall.bat
cmd /c artp\unInstall.bat
cmd /c Backlash\unInstall.bat
cmd /c Bias\unInstall.bat
cmd /c CapturePresentation\unInstall.bat
cmd /c ConstantValue\unInstall.bat
cmd /c ConvertImage\unInstall.bat
cmd /c CoulombAndViscousFriction\unInstall.bat
cmd /c DeadZone\unInstall.bat
cmd /c DemuxFunction\unInstall.bat
cmd /c Derivative\unInstall.bat
cmd /c Gain\unInstall.bat
cmd /c IfElse\unInstall.bat
cmd /c Integrator\unInstall.bat
cmd /c MinMaxFunction\unInstall.bat
cmd /c MuxFunction\unInstall.bat
cmd /c PIDController\unInstall.bat
cmd /c Polynomial\unInstall.bat
cmd /c PresentationView\unInstall.bat
cmd /c ProductFunction\unInstall.bat
cmd /c PulseGenerator\unInstall.bat
cmd /c RampFunction\unInstall.bat
cmd /c RandomNumber\unInstall.bat
cmd /c RateLimiter\unInstall.bat
cmd /c Relay\unInstall.bat
cmd /c RMC\unInstall.bat
cmd /c RobotArmSimulator\unInstall.bat
cmd /c Saturation\unInstall.bat
cmd /c Scope\unInstall.bat
cmd /c SignFunction\unInstall.bat
cmd /c SineWave\unInstall.bat
cmd /c SqrtFunction\unInstall.bat
cmd /c StepFunction\unInstall.bat
cmd /c SumFunction\unInstall.bat
cmd /c TrigonometricFunction\unInstall.bat
cmd /c UnaryMinus\unInstall.bat
cmd /c UniformRandomNumber\unInstall.bat
cmd /c WrapToZero\unInstall.bat
cmd /c MyFirstComponent\unInstall.bat
