cd /d %~dp0
cmd /c AbsFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c ArmController\Visual_Studio_8_2005_Genarate.bat
cmd /c artp\Visual_Studio_8_2005_Genarate.bat
cmd /c Backlash\Visual_Studio_8_2005_Genarate.bat
cmd /c Bias\Visual_Studio_8_2005_Genarate.bat
cmd /c CapturePresentation\Visual_Studio_8_2005_Genarate.bat
cmd /c ConstantValue\Visual_Studio_8_2005_Genarate.bat
cmd /c ConvertImage\Visual_Studio_8_2005_Genarate.bat
cmd /c CoulombAndViscousFriction\Visual_Studio_8_2005_Genarate.bat
cmd /c DeadZone\Visual_Studio_8_2005_Genarate.bat
cmd /c DemuxFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c Derivative\Visual_Studio_8_2005_Genarate.bat
cmd /c Gain\Visual_Studio_8_2005_Genarate.bat
cmd /c IfElse\Visual_Studio_8_2005_Genarate.bat
cmd /c Integrator\Visual_Studio_8_2005_Genarate.bat
cmd /c MinMaxFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c MuxFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c PIDController\Visual_Studio_8_2005_Genarate.bat
cmd /c Polynomial\Visual_Studio_8_2005_Genarate.bat
cmd /c PresentationView\Visual_Studio_8_2005_Genarate.bat
cmd /c ProductFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c PulseGenerator\Visual_Studio_8_2005_Genarate.bat
cmd /c RampFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c RandomNumber\Visual_Studio_8_2005_Genarate.bat
cmd /c RateLimiter\Visual_Studio_8_2005_Genarate.bat
cmd /c Relay\Visual_Studio_8_2005_Genarate.bat
cmd /c RMC\Visual_Studio_8_2005_Genarate.bat
cmd /c RobotArmSimulator\Visual_Studio_8_2005_Genarate.bat
cmd /c Saturation\Visual_Studio_8_2005_Genarate.bat
cmd /c Scope\Visual_Studio_8_2005_Genarate.bat
cmd /c SignFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c SineWave\Visual_Studio_8_2005_Genarate.bat
cmd /c SqrtFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c StepFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c SumFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c TrigonometricFunction\Visual_Studio_8_2005_Genarate.bat
cmd /c UnaryMinus\Visual_Studio_8_2005_Genarate.bat
cmd /c UniformRandomNumber\Visual_Studio_8_2005_Genarate.bat
cmd /c WrapToZero\Visual_Studio_8_2005_Genarate.bat
cmd /c MyFirstComponent\Visual_Studio_8_2005_Genarate.bat
cmd /c testEC\Visual_Studio_8_2005_Genarate.bat
