// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "SpreadSheet.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static CORBA::TypeCode_ptr _0RL_tc_StringSeq = CORBA::TypeCode::PR_alias_tc("IDL:StringSeq:1.0", "StringSeq", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_string_tc(0, &_0RL_tcTrack), &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr _tc_StringSeq = _0RL_tc_StringSeq;

static CORBA::TypeCode_ptr _0RL_tc_StringList = CORBA::TypeCode::PR_alias_tc("IDL:StringList:1.0", "StringList", CORBA::TypeCode::PR_sequence_tc(0, _0RL_tc_StringSeq, &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr _tc_StringList = _0RL_tc_StringList;

static CORBA::TypeCode_ptr _0RL_tc_FloatSeq = CORBA::TypeCode::PR_alias_tc("IDL:FloatSeq:1.0", "FloatSeq", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_float_tc(), &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr _tc_FloatSeq = _0RL_tc_FloatSeq;

static CORBA::TypeCode_ptr _0RL_tc_FloatList = CORBA::TypeCode::PR_alias_tc("IDL:FloatList:1.0", "FloatList", CORBA::TypeCode::PR_sequence_tc(0, _0RL_tc_FloatSeq, &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr _tc_FloatList = _0RL_tc_FloatList;

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace SpreadSheet { 
  const ::CORBA::TypeCode_ptr _tc_mSpreadSheet = CORBA::TypeCode::PR_interface_tc("IDL:SpreadSheet/mSpreadSheet:1.0", "mSpreadSheet", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr SpreadSheet::_tc_mSpreadSheet = CORBA::TypeCode::PR_interface_tc("IDL:SpreadSheet/mSpreadSheet:1.0", "mSpreadSheet", &_0RL_tcTrack);
#endif

static void _0RL_StringSeq_marshal_fn(cdrStream& _s, void* _v)
{
  StringSeq* _p = (StringSeq*)_v;
  *_p >>= _s;
}
static void _0RL_StringSeq_unmarshal_fn(cdrStream& _s, void*& _v)
{
  StringSeq* _p = new StringSeq;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_StringSeq_destructor_fn(void* _v)
{
  StringSeq* _p = (StringSeq*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const StringSeq& _s)
{
  StringSeq* _p = new StringSeq(_s);
  _a.PR_insert(_0RL_tc_StringSeq,
               _0RL_StringSeq_marshal_fn,
               _0RL_StringSeq_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, StringSeq* _sp)
{
  _a.PR_insert(_0RL_tc_StringSeq,
               _0RL_StringSeq_marshal_fn,
               _0RL_StringSeq_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, StringSeq*& _sp)
{
  return _a >>= (const StringSeq*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const StringSeq*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_StringSeq,
                    _0RL_StringSeq_unmarshal_fn,
                    _0RL_StringSeq_marshal_fn,
                    _0RL_StringSeq_destructor_fn,
                    _v)) {
    _sp = (const StringSeq*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_StringList_marshal_fn(cdrStream& _s, void* _v)
{
  StringList* _p = (StringList*)_v;
  *_p >>= _s;
}
static void _0RL_StringList_unmarshal_fn(cdrStream& _s, void*& _v)
{
  StringList* _p = new StringList;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_StringList_destructor_fn(void* _v)
{
  StringList* _p = (StringList*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const StringList& _s)
{
  StringList* _p = new StringList(_s);
  _a.PR_insert(_0RL_tc_StringList,
               _0RL_StringList_marshal_fn,
               _0RL_StringList_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, StringList* _sp)
{
  _a.PR_insert(_0RL_tc_StringList,
               _0RL_StringList_marshal_fn,
               _0RL_StringList_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, StringList*& _sp)
{
  return _a >>= (const StringList*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const StringList*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_StringList,
                    _0RL_StringList_unmarshal_fn,
                    _0RL_StringList_marshal_fn,
                    _0RL_StringList_destructor_fn,
                    _v)) {
    _sp = (const StringList*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_FloatSeq_marshal_fn(cdrStream& _s, void* _v)
{
  FloatSeq* _p = (FloatSeq*)_v;
  *_p >>= _s;
}
static void _0RL_FloatSeq_unmarshal_fn(cdrStream& _s, void*& _v)
{
  FloatSeq* _p = new FloatSeq;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_FloatSeq_destructor_fn(void* _v)
{
  FloatSeq* _p = (FloatSeq*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const FloatSeq& _s)
{
  FloatSeq* _p = new FloatSeq(_s);
  _a.PR_insert(_0RL_tc_FloatSeq,
               _0RL_FloatSeq_marshal_fn,
               _0RL_FloatSeq_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, FloatSeq* _sp)
{
  _a.PR_insert(_0RL_tc_FloatSeq,
               _0RL_FloatSeq_marshal_fn,
               _0RL_FloatSeq_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, FloatSeq*& _sp)
{
  return _a >>= (const FloatSeq*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const FloatSeq*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_FloatSeq,
                    _0RL_FloatSeq_unmarshal_fn,
                    _0RL_FloatSeq_marshal_fn,
                    _0RL_FloatSeq_destructor_fn,
                    _v)) {
    _sp = (const FloatSeq*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_FloatList_marshal_fn(cdrStream& _s, void* _v)
{
  FloatList* _p = (FloatList*)_v;
  *_p >>= _s;
}
static void _0RL_FloatList_unmarshal_fn(cdrStream& _s, void*& _v)
{
  FloatList* _p = new FloatList;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_FloatList_destructor_fn(void* _v)
{
  FloatList* _p = (FloatList*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const FloatList& _s)
{
  FloatList* _p = new FloatList(_s);
  _a.PR_insert(_0RL_tc_FloatList,
               _0RL_FloatList_marshal_fn,
               _0RL_FloatList_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, FloatList* _sp)
{
  _a.PR_insert(_0RL_tc_FloatList,
               _0RL_FloatList_marshal_fn,
               _0RL_FloatList_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, FloatList*& _sp)
{
  return _a >>= (const FloatList*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const FloatList*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_FloatList,
                    _0RL_FloatList_unmarshal_fn,
                    _0RL_FloatList_marshal_fn,
                    _0RL_FloatList_destructor_fn,
                    _v)) {
    _sp = (const FloatList*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_SpreadSheet_mmSpreadSheet_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_SpreadSheet_mmSpreadSheet_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(SpreadSheet::mSpreadSheet::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_SpreadSheet_mmSpreadSheet_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, SpreadSheet::mSpreadSheet_ptr _o)
{
  SpreadSheet::mSpreadSheet_ptr _no = SpreadSheet::mSpreadSheet::_duplicate(_o);
  _a.PR_insert(SpreadSheet::_tc_mSpreadSheet,
               _0RL_SpreadSheet_mmSpreadSheet_marshal_fn,
               _0RL_SpreadSheet_mmSpreadSheet_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, SpreadSheet::mSpreadSheet_ptr* _op)
{
  _a.PR_insert(SpreadSheet::_tc_mSpreadSheet,
               _0RL_SpreadSheet_mmSpreadSheet_marshal_fn,
               _0RL_SpreadSheet_mmSpreadSheet_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = SpreadSheet::mSpreadSheet::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, SpreadSheet::mSpreadSheet_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(SpreadSheet::_tc_mSpreadSheet,
                    _0RL_SpreadSheet_mmSpreadSheet_unmarshal_fn,
                    _0RL_SpreadSheet_mmSpreadSheet_marshal_fn,
                    _0RL_SpreadSheet_mmSpreadSheet_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (SpreadSheet::mSpreadSheet_ptr)_r->_ptrToObjRef(SpreadSheet::mSpreadSheet::_PD_repoId);
    else
      _o = SpreadSheet::mSpreadSheet::_nil();
    return 1;
  }
  return 0;
}

